version: '3'

services:
  app:
    image: nginx
    ports:
      - 80:8443    # localhost only by default
    volumes: ./
    # command: ""

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '443:443'
    links:
      - app
    depends_on:
      - app
    restart: unless-stopped
    environment:
      DOMAINS: '54.95.56.31 -> http://app:8443'
      STAGE: local
      SERVER_NAMES_HASH_BUCKET_SIZE: 128
